(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Title:: *)
(*Erzeugung von "farbigem Rauschen" (normalverteilt)*)


PlotSample[sample_List]:=
ListLinePlot[
sample,
PlotLabel->"\[Mu] = "<>
	ToString[Mean[sample]]
<>" ,\[Sigma] = "<>
ToString[
StandardDeviation[sample]
],
AxesLabel->{TraditionalForm["n"],"\!\(\*SubscriptBox[\"X\", \"n\"]\)"}
];


(* ::Subsection:: *)
(*Gleichverteiltes wei\[SZ]es Rauschen*)


uniform=RandomReal[1,200];
PlotSample[uniform]



(* ::Subsection:: *)
(*Normalverteiltes wei\[SZ]es Rauschen*)


normal=RandomReal[
NormalDistribution[0,1],
200];
PlotSample[normal]


(* ::Text:: *)
(*Umwandlung in 1/f-Rauschen:*)


ftnorm=Fourier[normal];
pink=InverseFourier[Table[1/i,{i,200}]*ftnorm];
PlotSample[pink]



